services:

  ## Magasin
  # magasin:
  #   build: ./magasin
  #   environment:
  #     - DATABASE_URL=postgresql://log430:laboratoire430@postgres_magasin:5432/log430_magasin
  #   depends_on:
  #     - postgres_magasin
  
  ## Magasin en Ligne
  # magasin_enligne:
  #   build: ./magasin_enligne
  #   ports:
  #   - "8010:8000"
  #   environment:
  #     - SERVER_HOST=0.0.0.0
  #     - SERVER_PORT=8000
  #     - DATABASE_URL=postgresql://log430:laboratoire430@postgres_magasin:5432/log430_magasin
  #   depends_on:
  #     - postgres_magasin
  
  # ## Maison mere
  # maison_mere:
  #   build: ./maison_mere
  #   ports:
  #     - "8020:8000"
  #   environment:
  #     - SERVER_HOST=0.0.0.0
  #     - SERVER_PORT=8000

  # ## Centre Logistique
  centre_logistique_app_1:
    build: ./centre_logistique
    environment:
      - SERVER_HOST=0.0.0.0
      - SERVER_PORT=8000
      - DATABASE_URL=postgresql://log430:laboratoire430@postgres_centre_logistique:5432/log430_cl
    depends_on:
      - postgres_centre_logistique

  # centre_logistique_app_2:
  #   build: ./centre_logistique
  #   environment:
  #     - SERVER_HOST=0.0.0.0
  #     - SERVER_PORT=8000
  #     - DATABASE_URL=postgresql://log430:laboratoire430@postgres_centre_logistique:5432/log430_cl
  #   depends_on:
  #     - postgres_centre_logistique
  
  nginx:
    image: nginx:latest
    ports:
      - "8000:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - centre_logistique_app_1
      # - centre_logistique_app_2

  prometheus:
    image: prom/prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro
    ports:
      - "9090:9090"
    restart: unless-stopped

  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"
    restart: unless-stopped
    depends_on:
      - prometheus 

  node_exporter:
    image: prom/node-exporter:latest
    ports:
      - "9100:9100"
    restart: unless-stopped

  postgres_centre_logistique:
    image: postgres:13
    restart: unless-stopped
    environment:
      POSTGRES_USER: log430
      POSTGRES_PASSWORD: laboratoire430
      POSTGRES_DB: log430_cl
    ports:
      - "5434:5432"
  
  # postgres_magasin:
    # image: postgres:13
    # restart: unless-stopped
    # environment:
    #   POSTGRES_USER: log430
    #   POSTGRES_PASSWORD: laboratoire430
    #   POSTGRES_DB: log430_magasin
    # ports:
    #   - "5435:5432"