global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'centre_logistique'
    metrics_path: /api/metrics
    static_configs:
    - targets: ['centre_logistique_app_1:8000', 'centre_logistique_app_2:8000']
  
  - job_name: 'node_exporter'
    static_configs:
      - targets: ['node_exporter:9100']
