{
 "title": "Centre_logistique 1",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "auto",
 "panels": [
  {
   "title": "505",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "rate(centre_logistique_http_requests_total{status=~\"5..\"}[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "404",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "rate(centre_logistique_http_requests_total{status=~\"4..\"}[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Mémoire (% utilisée)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "((node_memory_MemTotal_bytes - node_memory_MemAvailable_bytes) / node_memory_MemTotal_bytes) * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": " CPU (%)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "100 - (avg by (instance) (rate(node_cpu_seconds_total{mode=\"idle\"}[1m])) * 100)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Trafic",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "rate(centre_logistique_http_requests_total[1m])",
     "legendFormat": "trafic"
    }
   ]
  },
  {
   "title": "Average Latence",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "expr": "rate(centre_logistique_http_request_duration_seconds_sum[1m])\r\n/\r\nrate(centre_logistique_http_request_duration_seconds_count[1m])",
     "legendFormat": "average latence"
    }
   ]
  },
  {
   "title": "Latence 0.95",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, rate(centre_logistique_http_request_duration_seconds_bucket[1m]))",
     "legendFormat": "0.95 latence"
    }
   ]
  },
  {
   "title": "Latence 0.99",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, rate(centre_logistique_http_request_duration_seconds_bucket[1m]))",
     "legendFormat": "0.99 latence"
    }
   ]
  }
 ]
}