[package]
name = "magasin"
version = "0.1.0"
edition = "2024"

[dependencies]
chrono = "0.4"
diesel = { version = "2.2.11", features = ["postgres", "r2d2", "chrono"] }
dotenvy = "0.15"
once_cell = "1.18"