@startuml
node "Magasin" as Magasin {
  artifact "Application Magasin\n(main.rs)" as AppMagasin
  database "PostgreSQL\n(db.rs)" as DbMagasin
}
node "Magasin en ligne" as MagasinEnLigne {
  artifact "Application MagasinEnLigne\n(main.rs)" as AppMagasinEnLigne
  database "PostgreSQL\n(db.rs)" as DbMagasinEnLigne
}
node "Maison mere" as MaisonMere {
  artifact "Application MaisonMere\n(main.rs)" as AppMaisonMere
}

node "Centre logistique" as Server {
  database "PostgreSQL Centrale" as PostgresCentral
  artifact "Application CentreLogistique\n(main.rs)" as AppCentreLogistique
}

Magasin --> AppCentreLogistique : Requêtes HTTP/Synchronisation
MagasinEnLigne --> AppCentreLogistique : Requêtes HTTP/Synchronisation
MaisonMere --> AppCentreLogistique : Requêtes des données
AppCentreLogistique --> PostgresCentral : Accès base de données
@enduml
