@startuml
actor Client
participant "Login"
participant "Menu"
participant "Menu_Achat"
participant "PostgreSQL"
participant "Produit"

Client -> "Login" : login()
"Login" -> "Menu" : menu_principal()
"Menu" -> "Menu_Achat" : menu_achat()
"Menu_Achat" -> "PostgreSQL" : session()
"PostgreSQL" -> "Produit" : add()
"Produit" -> "Menu_Achat" : ok
"Menu_Achat" -> "Client" : ok
@enduml