@startuml
skinparam componentStyle rectangle

package "Application de la console" {

  package "Présentation" {
    component "views"
    component "main.rs"
  }

  package "Logique métier" {
    component "achat_controller.rs"
    component "consulter_controller.rs"
    component "menu_controller.rs"
    component "login_controller.rs"
    component "retour_controller.rs"
    component "recherche_controller.rs"
  }

  package "Persistance" {
    component "Diesel ORM"
    component "PostgreSQL"
    component "Model (Produit, Client, Inventaire, Transaction)"
  }

  "main.rs" --> "achat_controller.rs"
  "achat_controller.rs" --> "Modèles (Produit, Client, Inventaire, Transaction)"
  "Modèles (Produit, Client, Inventaire, Transaction)" --> "Diesel ORM"
  "Diesel ORM" --> "PostgreSQL"
}

@enduml
