name: CI - Maison mere

on:
  push:
    branches: [ main ]
    paths:
      - 'maison_mere/**'
      - '.github/workflows/ci_maison_mere.yml'
  pull_request:
    branches: [ main ]
    paths:
      - 'maison_mere/**'
      - '.github/workflows/ci_maison_mere.yml'

jobs:
  build-test-lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      - name: Cache Cargo registry
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-cargo-

      - name: Build maison_mere
        run: cargo build -p maison_mere --verbose

      - name: Check formatting
        run: cargo fmt --all -- --check

      - name: Lint with Clippy
        run: cargo clippy -p maison_mere --all-targets --all-features -- -D warnings

      - name: Run tests
        run: cargo test -p maison_mere --verbose

      - name: Build Docker image
        run: |
          docker build -t centre_logistique:latest ./maison_mere
